### ISSUE TITLE
CorruptedWebSocketFrameException

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#138]
I think there might be a problem with getting very large responses from dshackle when endpoints are connected with WebSockets

Here is the error I see in Dshackle
```
2021-28-12 19:22:21.774 | WARN  |          FluxReceive | [id:0a5c8940-1, L:/172.19.0.4:37732 ! R:archive08.archivenode.io/47.186.103.49:8548] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 5242880 has been exceeded.
```

Here is the request that generated the error:
```
curl -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0xbe0f2d","toBlock":"0xbe363c","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",null,null],"address":"0x6b175474e89094c44da98b954eedeac495271d0f"}]}'
```

The response from the endpoints themselves work fine if I send it directly, however the response is 25MB in size and it seems like dshackle doesn't like receiving large frames over WebSocket?

**Comment by splix** [comment]
Right, Dshackle has a limit of 5MB per WS Frame (as defined here: https://github.com/emeraldpay/dshackle/blob/master/src/main/kotlin/io/emeraldpay/dshackle/upstream/ethereum/WsConnection.kt#L84). 

I thought 5Mb is too large already because it not supposed to go as one single frame. WebSocket sender should split large messages into multiple frames instead. Like 25 of 1mb frames for that large JSON, but Geth decides to send huge blobs instead.

I guess I should increase it, or better make it configurable. Also the total size for the whole message is 15Mb, which seems to be too small anyway.

**Comment by splix** [comment]
Actually, it's already configurable: https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#upstream-json (see `ws.frameSize`, etc)
