### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by PDVJAM** [emeraldpay/dshackle#229]
Hey. I just noticed that in the reference doc there are some changes, ie:
```
cluster:
  defaults:
    - blockchains:
        - ethereum
      min-peers: 10
    - blockchains:
        - kovan
      min-peers: 3
  include:
    - "upstreams-extra.yaml"
  upstreams:
    - id: local
      blockchain: ethereum
```

Previously it was:
```
cluster:
  defaults:
    - chains:
        - ethereum
      min-peers: 10
    - chains:
        - kovan
      min-peers: 3
  include:
    - "upstreams-extra.yaml"
  upstreams:
    - id: local
      chain: ethereum
```

So chains became blockchains.
I have tried with blockchains and dshackle doesn't see such upstreams
```
2023-02-03 15:54:28.857 | ERROR |  ConfiguredUpstreams | Chain is unknown: null
2023-02-03 15:54:28.858 | ERROR |  ConfiguredUpstreams | Chain is unknown: null
2023-02-03 15:54:28.858 | ERROR |  ConfiguredUpstreams | Chain is unknown: null
2023-02-03 15:54:28.858 | ERROR |  ConfiguredUpstreams | Chain is unknown: null
```

So probably its either new build wasn't uploaded or the new documentation wrong.

**Comment by benjlevesque** [comment]
I ran into a similar problem by running dshackle on docker; in my case I had to rename `upstreams.blockchain` to `upstreams.chain`. There should be a new release to avoid the confusion...

**Comment by splix** [comment]
Yeah, the docs folder is for `master` branch and it may be confusing because some options were added/renamed after the release. I guess the main repo page should point to the release docs, not development branch.

The current release docs are at https://github.com/emeraldpay/dshackle/tree/v0.13.1/docs

Release v0.13.x has `chains` option. But with the next `v0.14` it should be `blockchains` or `chains` for backward compatibility. Some other options are also renamed. It shouldn't make any trouble after upgrading to v0.14 because it accepts the previous names but only new names are going to be mentioned in the docs.
