### ISSUE TITLE
Is eth_syncing required?

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#54]
From a technical standpoint is `eth_syncing` required for dshackle to function properly? The reason I ask is because Turbo-Geth currently doesn't support `eth_syncing`, which I think is why Turbo-Geth nodes are always listed as `UNAVAILABLE` in the `dshackle` logs/output?

I think I could add `disable-validation: true` but I fear that would cause dshackle to not mark it as down if it is actually down.

I've submitted a feature request to the Turbo-Geth team to add `eth_syncing` but I wanted to get your thoughts on the topic and/or ask if there's a better workaround. I would think that doing `eth_blockNumber` and comparing it to other configured nodes would be enough, but I'm not sure.

**Comment by splix** [comment]
You may try to disable validation, technically it should work and when the upstream is down it will retry with others. But it may degrade performance (when down) or quality (when syncing, but dshackle doesn't know about it).

Dshackle actually does check for block numbers too, but with validation disabled it's unreliable, because it supposed to be part of the same logic. Need to check the code though, that's some setup I didn't think about when designed that part.

**Comment by AskAlexSharov** [comment]
Data field inside eth_syncing is useful for you?

**Comment by splix** [comment]
@AskAlexSharov it doesn't use the result object values, only check if it's a boolean or an object. In addition to `eth_syncing` the Dshackle uses `net_peerCount` during the validation.

**Comment by AskAlexSharov** [comment]
thank you, guys. I added versions of eth_syncing and net_peerCount which are enough for your use-case.
