### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#57]
Recently, I've noticed a huge flurry of errors that look like this:

```
2020-22-09 23:46:34.077 | WARN  |          FluxReceive | [id: 0x228b9b97, L:/172.19.0.3:8545 - R:/172.19.0.5:34856] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
```

Any ideas?

**Comment by splix** [comment]
It seems that the connection to an upstream was terminated by the other side.

I had same issue when I was trying to make too many requests. Like thousands, for example when indexing into external db. The Dshackle tries to recover and retries the request, but doesn't really help because the upstream is simply overloaded and drops all requests. And you get the same error again. Some implementations even crash if you have too many requests. It something that might be fixed with #13 (in my case I fixed that by limiting the requests rate on client side).

I guess it's your case too, bunch of simultaneous requests causing upstream to drop a connection.

**Comment by MysticRyuujin** [comment]
I'm still getting a ton of these, even against Turbo-Geth now.

I do not in any way think this is related to rate limiting...

It could be, I guess, but we're just not processing THAT many requests, and we're load balancing them to like 3 or 4 nodes at a time.

**Comment by MysticRyuujin** [comment]
Heh, I think I figured it out...

https://discourse.haproxy.org/t/haproxy-1-5-4-1-5-18-is-sending-rst-ack-in-for-closure-to-httpchk-instead-of-fin-ack/474/3

haproxy is doing health checks against dshackle in the form of:
```
option httpchk POST /eth HTTP/1.1\r\nContent-Type:\ application/json\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":1,\"params\":[],\"method\":\"eth_blockNumber\"}
```
haproxy is then immediately sending `RST,ACK` instead of `FIN,ACK` and dshackle is getting upset about that...

**Comment by splix** [comment]
ah, that's interesting, I think I have some ideas now how to fix it. thank you!

**Comment by splix** [comment]
Rel: https://github.com/reactor/reactor-netty/issues/564, but that's for client side. For the server side the only solution is seems to be ignoring the error.
